"""Generating the instruction files coding agents actually read.

An agent opening a game project does not know what a PyGuara scene is,
which components exist, how to run the tests, or that Studio can be driven
over MCP. All of that is derivable from the project, and writing it by
hand means it is wrong within a month.

**One canonical file, thin per-tool shims.** The landscape as it stands:

- `AGENTS.md` is the cross-tool standard, stewarded by the Agentic AI
  Foundation. The nearest file in the directory tree wins for the code
  being edited, and the format has no required fields -- it is plain
  Markdown with whatever headings suit.
- **Claude Code** reads `CLAUDE.md`, and falls back to `AGENTS.md` only
  when there is no `CLAUDE.md`. It does not merge them: if both exist,
  `CLAUDE.md` wins outright and `AGENTS.md` is never consulted. So the
  shim is an `@AGENTS.md` **import line**, not a copy -- a copy is a
  second source of truth that silently rots.
- **Cursor** uses `.cursor/rules/*.mdc`; `.cursorrules` is legacy.
- **Gemini CLI** uses `GEMINI.md`.
- **Codex** truncates an instruction file at 32 KiB
  (`project_doc_max_bytes`) and prefers `AGENTS.override.md` in the same
  directory, which is why the generator never writes one: that filename
  belongs to whoever needs to override what this produces.

**Generated regions are fenced, and nothing outside them is touched.**
This is the rule everything else bends around. A project's instruction
file is mostly hand-written knowledge -- the reason a system is the way it
is, the thing that broke last time -- and a generator that overwrites it
is a generator nobody runs twice. Regeneration replaces what is between
the markers and leaves every other byte alone.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from enum import Enum
from pathlib import Path
from typing import Any

from pyguara.log import get_logger
from pyguara.prefabs.registry import ComponentRegistry
from pyguara.studio.model.projectmap import ProjectMap, build_project_map

logger = get_logger(__name__)

BEGIN_MARKER = "<!-- BEGIN GENERATED BY PYGUARA STUDIO -- edit outside this block -->"
"""Opens a generated region.

The instruction to the reader is in the marker itself, because the person
who needs it is looking at the file, not at this module.
"""

END_MARKER = "<!-- END GENERATED BY PYGUARA STUDIO -->"
"""Closes a generated region."""

CODEX_BUDGET = 32 * 1024
"""Codex's default `project_doc_max_bytes`.

An instruction file past this is silently truncated, so the generator
warns rather than letting a project discover it when an agent stops
knowing the second half of its own conventions.
"""

AGENTS_FILE = "AGENTS.md"
"""The canonical instruction file every tool but Claude and Gemini reads."""

CURSOR_RULE_PATH = ".cursor/rules/pyguara.mdc"
"""Cursor's rule file. The directory format; `.cursorrules` is legacy."""


class ShimKind(str, Enum):
    """Which tool a shim file is for."""

    CLAUDE = "claude"
    """`CLAUDE.md`. Claude Code never merges it with `AGENTS.md`."""

    GEMINI = "gemini"
    """`GEMINI.md`, which Gemini CLI reads instead of `AGENTS.md`."""

    CURSOR = "cursor"
    """`.cursor/rules/pyguara.mdc`."""


@dataclass(frozen=True)
class InstructionFile:
    """One file the generator would write.

    Attributes:
        path: Where it goes, relative to the project root.
        content: Its full intended contents, hand-written parts included.
        generated: Just the generated region, for a drift check that
            ignores hand edits outside it.
    """

    path: str
    content: str
    generated: str

    @property
    def size(self) -> int:
        """How many bytes the file would be, as UTF-8."""
        return len(self.content.encode("utf-8"))


@dataclass(frozen=True)
class InstructionSet:
    """Everything the generator would write, and what it noticed.

    Attributes:
        files: The files, canonical first.
        warnings: Things worth saying out loud -- a file over Codex's
            truncation limit, a project with nothing in it.
    """

    files: tuple[InstructionFile, ...] = ()
    warnings: tuple[str, ...] = ()

    def file(self, path: str) -> InstructionFile | None:
        """Look one file up by path.

        Args:
            path: The relative path.

        Returns:
            The file, or None.
        """
        for candidate in self.files:
            if candidate.path == path:
                return candidate
        return None


@dataclass(frozen=True)
class Drift:
    """One file whose generated region is out of date.

    Attributes:
        path: The file, relative to the project root.
        reason: What differs -- missing, no markers, or stale content.
    """

    path: str
    reason: str


@dataclass
class ProjectFacts:
    """What the generated prose is written from.

    Separated from the rendering so a caller can describe a project the
    walk cannot see -- a monorepo package, a project whose tests run
    through something unusual -- without reimplementing the renderer.

    Attributes:
        name: The project's name, for the title.
        summary: One or two sentences on what it is.
        project_map: The content inventory.
        commands: Shell commands worth knowing, as `(description, command)`.
        conventions: Project-specific rules, one per line.
    """

    name: str
    summary: str = ""
    project_map: ProjectMap | None = None
    commands: tuple[tuple[str, str], ...] = ()
    conventions: tuple[str, ...] = ()


def build_instructions(
    project_root: Path,
    *,
    registry: ComponentRegistry | None = None,
    facts: ProjectFacts | None = None,
    shims: tuple[ShimKind, ...] = (
        ShimKind.CLAUDE,
        ShimKind.GEMINI,
        ShimKind.CURSOR,
    ),
    budget: int = CODEX_BUDGET,
) -> InstructionSet:
    """Build the instruction files for `project_root`.

    Existing files are read and merged: everything outside the generated
    markers is preserved exactly, which is what makes this safe to run on
    a project whose `CLAUDE.md` is mostly hand-written knowledge.

    Args:
        project_root: The project directory.
        registry: The component registry, for the component vocabulary.
        facts: What to write. Discovered from the project when omitted.
        shims: Which per-tool shim files to produce.
        budget: Warn when the canonical file exceeds this many bytes.
            Defaults to Codex's truncation limit.

    Returns:
        The files and any warnings.

    Raises:
        ValueError: If `project_root` is not a directory.
    """
    project_root = project_root.resolve()
    if not project_root.is_dir():
        raise ValueError(f"{project_root} is not a directory.")

    if facts is None:
        facts = discover_facts(project_root, registry=registry)

    warnings: list[str] = []
    generated = _render_canonical(facts)
    canonical = InstructionFile(
        path=AGENTS_FILE,
        content=merge_generated(
            _read(project_root / AGENTS_FILE), generated, header=_title(facts)
        ),
        generated=generated,
    )

    files: list[InstructionFile] = [canonical]
    for shim in shims:
        files.append(_build_shim(project_root, shim))

    if canonical.size > budget:
        warnings.append(
            f"{AGENTS_FILE} is {canonical.size} bytes, over the "
            f"{budget}-byte limit Codex truncates at. Move detail into a "
            f"linked reference file, or into a nested AGENTS.md beside the "
            f"code it describes -- the nearest file in the tree wins."
        )
    if facts.project_map is not None and not (
        facts.project_map.scenes or facts.project_map.prefabs
    ):
        warnings.append(
            "No scenes or prefabs were found, so the generated file "
            "describes the toolchain but not the content."
        )

    return InstructionSet(files=tuple(files), warnings=tuple(warnings))


def discover_facts(
    project_root: Path, *, registry: ComponentRegistry | None = None
) -> ProjectFacts:
    """Work out what to say about a project by looking at it.

    Args:
        project_root: The project directory.
        registry: The component registry, for the component vocabulary.

    Returns:
        The facts, with commands chosen from the tooling actually present
        -- `uv run pytest` where there is a `uv.lock`, plain `pytest`
        otherwise. A command a project cannot run is worse than none: an
        agent will try it, and spend a turn finding out.

        The content inventory is included unless the project turns it off
        with `[tool.pyguara.agents] inventory = false`, which a library or
        the engine itself wants: it has no scenes to inventory, and the
        asset counts change whenever any image does, so the generated file
        would churn for no gain.
    """
    settings = _declared_settings(project_root)
    project_map = (
        build_project_map(project_root, registry=registry)
        if settings.get("inventory", True)
        else None
    )
    uses_uv = (project_root / "uv.lock").exists()
    summary = _summary_from(settings)
    runner = "uv run " if uses_uv else ""

    commands: list[tuple[str, str]] = []
    if (project_root / "pyproject.toml").exists():
        commands.append(
            (
                "Install dependencies",
                "uv sync --all-extras" if uses_uv else "pip install -e .[dev]",
            )
        )
    if (project_root / "tests").is_dir():
        commands.append(("Run the tests", f"{runner}pytest"))
    if _has_ruff(project_root):
        commands.append(("Lint", f"{runner}ruff check ."))
        commands.append(("Format", f"{runner}ruff format ."))
    if _has_mypy(project_root):
        commands.append(("Type-check", f"{runner}mypy ."))

    return ProjectFacts(
        name=project_root.name,
        summary=summary,
        project_map=project_map,
        commands=tuple(commands),
    )


def _declared_settings(project_root: Path) -> dict[str, Any]:
    """Return the project's `[tool.pyguara.agents]` table.

    Read from `pyproject.toml` rather than taken as flags, so that
    `--check` agrees with the write without every flag being repeated. A
    summary that lived only on the command line made CI report drift
    against the very file it had generated -- the point of `--check`
    defeated by the first project that used one.

    Args:
        project_root: The project directory.

    Returns:
        The table, plus `description` from `[project]` under the key
        `_package_description`. Empty when there is no readable
        `pyproject.toml` -- a project with a broken one still gets
        instructions.
    """
    import tomllib

    pyproject = project_root / "pyproject.toml"
    try:
        data = tomllib.loads(pyproject.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, tomllib.TOMLDecodeError) as exc:
        logger.debug(f"Could not read {pyproject}: {exc}")
        return {}

    settings = dict(data.get("tool", {}).get("pyguara", {}).get("agents", {}))
    description = data.get("project", {}).get("description")
    if isinstance(description, str):
        settings["_package_description"] = description
    return settings


def _summary_from(settings: dict[str, Any]) -> str:
    """Return the summary a project declares, or "" for the default.

    Two sources, most specific first:

    1. `[tool.pyguara.agents] summary` -- written for agents.
    2. `[project] description` -- the package blurb, which is usually
       close enough and is already maintained.

    Args:
        settings: The table `_declared_settings` returned.

    Returns:
        The summary, or "" when the project declares none.
    """
    declared = settings.get("summary")
    if isinstance(declared, str) and declared.strip():
        return declared.strip()

    description = settings.get("_package_description")
    if isinstance(description, str) and description.strip():
        return description.strip()
    return ""


def merge_generated(existing: str | None, generated: str, *, header: str = "") -> str:
    """Put `generated` into `existing`, preserving everything else.

    The rule the whole module bends around. An instruction file is mostly
    hand-written knowledge -- why a system is the way it is, what broke
    last time -- and a generator that overwrites it is one nobody runs
    twice.

    Three cases:

    - **No file.** A new one is written: the header, then the region.
    - **A file with markers.** Only what is between them is replaced.
    - **A file without markers.** The region is appended, and not a byte
      of the existing text changes.

    Args:
        existing: The current contents, or None when there is no file.
        generated: The region to install, without markers.
        header: A title to write above the region in a brand-new file.

    Returns:
        The merged contents.
    """
    block = f"{BEGIN_MARKER}\n{generated.strip()}\n{END_MARKER}\n"

    if existing is None or not existing.strip():
        prefix = f"{header.strip()}\n\n" if header.strip() else ""
        return f"{prefix}{block}"

    pattern = re.compile(
        f"{re.escape(BEGIN_MARKER)}.*?{re.escape(END_MARKER)}\n?",
        re.DOTALL,
    )
    if pattern.search(existing):
        return pattern.sub(lambda _: block, existing, count=1)

    separator = (
        ""
        if existing.endswith("\n\n")
        else ("\n" if existing.endswith("\n") else "\n\n")
    )
    return f"{existing}{separator}{block}"


def extract_generated(content: str) -> str | None:
    """Return the generated region of `content`, or None if there is none.

    Args:
        content: A file's contents.

    Returns:
        The region between the markers, stripped, or None.
    """
    match = re.search(
        f"{re.escape(BEGIN_MARKER)}\n(.*?)\n{re.escape(END_MARKER)}",
        content,
        re.DOTALL,
    )
    return match.group(1).strip() if match else None


def write_instructions(
    project_root: Path, instructions: InstructionSet
) -> tuple[Path, ...]:
    """Write every file in `instructions` that is not already correct.

    Args:
        project_root: The project directory.
        instructions: What to write.

    Returns:
        The paths actually written, in the order they were written. A file
        whose content already matches is skipped, so running this twice
        touches nothing the second time -- which keeps it out of a git
        diff and out of a file watcher's way.
    """
    written: list[Path] = []
    for file in instructions.files:
        target = project_root / file.path
        if _read(target) == file.content:
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(file.content, encoding="utf-8")
        written.append(target)
        logger.info(f"Wrote {file.path}")
    return tuple(written)


def check_instructions(
    project_root: Path, instructions: InstructionSet
) -> tuple[Drift, ...]:
    """Report which files are missing or have a stale generated region.

    What a CI step runs. Only the generated region is compared, so a hand
    edit elsewhere in the file is not drift -- it is the point.

    Args:
        project_root: The project directory.
        instructions: What the files should contain.

    Returns:
        One `Drift` per file that is out of date. Empty means in sync.
    """
    drifts: list[Drift] = []
    for file in instructions.files:
        current = _read(project_root / file.path)
        if current is None:
            drifts.append(Drift(path=file.path, reason="missing"))
            continue

        found = extract_generated(current)
        if found is None:
            drifts.append(
                Drift(
                    path=file.path,
                    reason="no generated block; run the generator to add one",
                )
            )
            continue
        if found != file.generated.strip():
            drifts.append(Drift(path=file.path, reason="generated block is stale"))

    return tuple(drifts)


# ------------------------------------------------------------------
# Rendering
# ------------------------------------------------------------------


def _title(facts: ProjectFacts) -> str:
    """Return the heading for a brand-new canonical file.

    Args:
        facts: What is known about the project.

    Returns:
        A Markdown heading.
    """
    return f"# {facts.name}\n\nInstructions for coding agents working in this project."


def _render_canonical(facts: ProjectFacts) -> str:
    """Render the generated region of `AGENTS.md`.

    Ordered by what an agent needs first: what this is, how to run it,
    then the vocabulary, then the Studio surface. An agent that reads only
    the first screen should still be able to act.

    Args:
        facts: What to write.

    Returns:
        The Markdown region, without markers.
    """
    sections: list[str] = []

    if facts.summary:
        sections.append(facts.summary.strip())
    else:
        sections.append(
            f"`{facts.name}` is a game built on the PyGuara engine: a "
            f"code-first Python 2D engine with an Entity-Component-System "
            f"core, a dependency-injection container and an event bus. "
            f"Scenes, components and systems are authored in Python; the "
            f"data files beside them are things a human could have written "
            f"by hand."
        )

    if facts.commands:
        lines = ["## Commands", ""]
        for description, command in facts.commands:
            lines.append(f"- {description}: `{command}`")
        sections.append("\n".join(lines))

    sections.append(_render_engine_conventions())

    if facts.project_map is not None:
        rendered = facts.project_map.to_markdown(budget=6000)
        if rendered:
            sections.append(rendered)

    sections.append(_render_studio_section())

    if facts.conventions:
        lines = ["## Project conventions", ""]
        lines.extend(f"- {convention}" for convention in facts.conventions)
        sections.append("\n".join(lines))

    return "\n\n".join(sections)


def _render_engine_conventions() -> str:
    """Render the engine rules an agent will otherwise get wrong.

    Chosen by what actually trips a newcomer to this engine, not by what
    is architecturally interesting. Each one is a mistake worth one line
    of prevention.

    Returns:
        A Markdown section.
    """
    return "\n".join(
        [
            "## Engine conventions",
            "",
            "- **Components are data.** A component is a dataclass with no",
            "  methods; behaviour lives in a system or in free functions",
            "  beside it. `BaseComponent.__init_subclass__` raises at class",
            "  definition time if a component declares a method.",
            "- **Never import the rendering backend.** Game code uses the",
            "  `IRenderer` / `UIRenderer` protocols through the DI container.",
            "  A direct `import pygame` in game code is a layering break.",
            "- **Query through the manager.** `entity_manager.get_entities_with("
            "Transform, Sprite)`",
            "  is an indexed lookup; iterating every entity and testing is not.",
            "- **Mutating a component needs a notification.** After writing a",
            "  field, call `entity_manager.notify_component_changed(entity_id, "
            "ComponentType)`,",
            "  or anything mirroring it -- physics bodies, render batches, the",
            "  spatial index -- keeps the old value.",
            "- **One component of each type per entity.** Replacing one is a",
            "  remove followed by an add.",
            "- **Two kinds of parent.** `Transform` parenting is spatial;",
            "  `ChildOf` is ownership and cascades on destroy. Set `ChildOf`",
            "  through `entity_manager.set_parent()`, never `add_component`.",
            "- **Fixed vs variable update.** Physics and game logic run in",
            "  `fixed_update` at a constant rate; rendering and animation run",
            "  in `update` at the display rate.",
        ]
    )


def _render_studio_section() -> str:
    """Render how to drive the editor from an agent.

    The part an agent cannot discover: that the surface exists at all.

    Returns:
        A Markdown section.
    """
    return "\n".join(
        [
            "## Authoring through PyGuara Studio",
            "",
            "Studio exposes the scene as a set of operations, so a scene can",
            "be read and edited without a window. Two transports, the same",
            "operations behind both:",
            "",
            "```bash",
            "# JSON lines on stdio -- no extra dependency.",
            "pyguara studio ops",
            "",
            "# Model Context Protocol -- needs the `studio` extra.",
            "pyguara studio mcp",
            "```",
            "",
            "To wire the MCP server into an agent, point it at",
            "`pyguara studio mcp` as a stdio server.",
            "",
            "Working rules, which the operations themselves enforce:",
            "",
            "- Call `project_overview` first in an unfamiliar project, then",
            "  `scene_summary`. `scene_tree` is the full read and is large.",
            "- Call `component_schema` before setting a field on a component",
            "  type you have not used. It carries the field types, the",
            "  defaults, and an enum field's valid members.",
            "- Entities are named by id, and ids survive undo, redo and",
            "  reload -- an id from one call still means the same entity in",
            "  the next.",
            "- Every edit returns the diff it produced. Check your own work",
            "  from the reply rather than re-reading the scene.",
            "- Every edit is undoable through `history`, and every action,",
            "  including the failures, is in `journal`.",
            "- An error names the alternative. A wrong component or field",
            "  name comes back with the closest match, so correct from the",
            "  message rather than listing everything again.",
        ]
    )


def _build_shim(project_root: Path, shim: ShimKind) -> InstructionFile:
    """Build one per-tool shim that defers to the canonical file.

    An import line rather than a copy. Claude Code in particular never
    merges `CLAUDE.md` with `AGENTS.md` -- if both exist, `CLAUDE.md` wins
    outright -- so a copy would become a second source of truth that
    silently rots while appearing authoritative.

    Args:
        project_root: The project directory, for reading an existing file.
        shim: Which tool to write for.

    Returns:
        The file.
    """
    if shim is ShimKind.CURSOR:
        generated = "\n".join(
            [
                "Follow the instructions in @AGENTS.md.",
                "",
                "That file is generated from the project; edit it, not this one.",
            ]
        )
        header = "\n".join(
            [
                "---",
                "description: PyGuara project conventions",
                "alwaysApply: true",
                "---",
                "",
                "# PyGuara",
            ]
        )
        path = CURSOR_RULE_PATH
    else:
        tool = "Claude Code" if shim is ShimKind.CLAUDE else "Gemini CLI"
        other = "AGENTS.md"
        generated = "\n".join(
            [
                f"@{other}",
                "",
                f"{tool} reads this file rather than `{other}`, and does not",
                f"merge the two -- so `{other}` is imported above instead of",
                "being copied here. Add anything tool-specific outside the",
                "generated block; it will be preserved.",
            ]
        )
        header = f"# {project_root.name}"
        path = "CLAUDE.md" if shim is ShimKind.CLAUDE else "GEMINI.md"

    return InstructionFile(
        path=path,
        content=merge_generated(_read(project_root / path), generated, header=header),
        generated=generated,
    )


# ------------------------------------------------------------------
# Small helpers
# ------------------------------------------------------------------


def _read(path: Path) -> str | None:
    """Return a file's text, or None when it is absent or unreadable.

    Args:
        path: The file to read.

    Returns:
        Its contents, or None.
    """
    try:
        return path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return None


def _has_ruff(project_root: Path) -> bool:
    """Whether the project is configured for ruff.

    Args:
        project_root: The project directory.

    Returns:
        True when ruff appears in its configuration.
    """
    if (project_root / "ruff.toml").exists() or (project_root / ".ruff.toml").exists():
        return True
    pyproject = _read(project_root / "pyproject.toml")
    return pyproject is not None and "[tool.ruff" in pyproject


def _has_mypy(project_root: Path) -> bool:
    """Whether the project is configured for mypy.

    Args:
        project_root: The project directory.

    Returns:
        True when mypy appears in its configuration.
    """
    if (project_root / "mypy.ini").exists():
        return True
    pyproject = _read(project_root / "pyproject.toml")
    return pyproject is not None and "[tool.mypy" in pyproject


__all__ = [
    "AGENTS_FILE",
    "BEGIN_MARKER",
    "CODEX_BUDGET",
    "CURSOR_RULE_PATH",
    "END_MARKER",
    "Drift",
    "InstructionFile",
    "InstructionSet",
    "ProjectFacts",
    "ShimKind",
    "build_instructions",
    "check_instructions",
    "discover_facts",
    "extract_generated",
    "merge_generated",
    "write_instructions",
]
