"""GardenGridCanvas: the plot's click input and juice; drawing is elsewhere.

A deliberate, novel combination: no existing capstone clicks on *world*
content through the UI system. `pyguara.ui.components.canvas.Canvas`
exists for exactly this ("a mini-map, a model preview, a custom graph"),
and `UIManager` already routes every mouse event to whichever widget is
under the cursor via `_process_input` -- so the grid gets working,
focus-stack-aware mouse input for free by being a `Canvas` subclass,
instead of adding a second, unexercised raw-`InputManager` mouse path.
`Slider._process_input` is the closest existing precedent for the pattern,
not an exact one: nothing else turns a click into *game* state this way.

Rendering itself moved out of the UI pass in the fun-improvement roadmap's
Phase 5: `render()` (what `UIManager` calls) is a deliberate no-op, and
`render_world()` -- called directly by `scenes.GardenScene.render()` --
holds the real drawing, through the world `IRenderer` instead of
`UIRenderer`. Input routing (`_process_input`, `hover_cell`, the rect
`UIManager` hit-tests against) is entirely unaffected: nothing about
*where a click lands* changed, only *how the result gets drawn* -- see
`bootstrap.py` for why (the world pass is what post-process shaders can
see; the UI pass, still true for the tool dock and the HUD, is not).

Also owns the plot's visual feedback: a `juice.Motes` particle burst on
tilling, watering, harvesting, and every plant stage change (including the
first, "just planted" one), a spring-driven overshoot pop on a stage change,
a slow idle sway so a mature plot doesn't read as a field of static
stickers, a moisture tint on the soil itself so watering is something
a player can see, and (when an `AudioManager` is supplied) a matching sound
at every one of those beats. A static grid of coloured circles would prove
the simulation runs; it wouldn't read as *alive* the way every other
capstone's world does.
"""

from __future__ import annotations

import math
from collections.abc import Callable
from dataclasses import dataclass

from games.quintal_cerrado import art
from games.quintal_cerrado.components import AutomationComponent, PlantComponent
from games.quintal_cerrado.garden_grid import (
    GRID_HEIGHT,
    GRID_WIDTH,
    TILE_SIZE,
    GardenGrid,
)
from games.quintal_cerrado.juice import FloatingLabels, Motes
from games.quintal_cerrado.species import SPECIES_TABLE
from games.quintal_cerrado.structures import STRUCTURE_TABLE, area
from pyguara.animation.easing import EasingType
from pyguara.animation.tween import Tween
from pyguara.audio.manager import AudioManager
from pyguara.common.grid import Cell, cell_to_world, neighbors8
from pyguara.common.types import Color, Rect, Vector2
from pyguara.ecs.manager import EntityManager
from pyguara.graphics.protocols import IRenderer, UIRenderer
from pyguara.ui.components.canvas import Canvas
from pyguara.ui.types import UIEventType

_ASSETS = "games/quintal_cerrado/assets/audio"
"""Where the placeholder SFX generated by `generate_placeholder_sfx.py` live."""

SFX_TILL = f"{_ASSETS}/till.wav"
SFX_WATER = f"{_ASSETS}/water.wav"
SFX_PLANT = f"{_ASSETS}/plant.wav"
SFX_GROW_STAGE = f"{_ASSETS}/grow_stage.wav"
SFX_HARVEST = f"{_ASSETS}/harvest.wav"
SFX_COMPOST = f"{_ASSETS}/compost.wav"
SFX_SPRAY = f"{_ASSETS}/spray.wav"
SFX_INFESTED = f"{_ASSETS}/infested.wav"
SFX_DYING = f"{_ASSETS}/dying.wav"
SFX_BUILD = f"{_ASSETS}/build.wav"
SFX_SEED = f"{_ASSETS}/seed.wav"
SFX_DENIED = f"{_ASSETS}/denied.wav"
SFX_OUTBREAK_START = f"{_ASSETS}/outbreak_start.wav"
SFX_OUTBREAK_RESOLVED = f"{_ASSETS}/outbreak_resolved.wav"
SFX_SOLAR_INCOME = f"{_ASSETS}/solar_income.wav"

TILL_DUST = Color(196, 158, 110)
WATER_DROPLET = Color(120, 180, 200)
HARVEST_GOLD = Color(240, 210, 130)
SEED_COLOR = Color(196, 176, 128)
COMPOST_COLOR = Color(126, 150, 88)
SPRAY_COLOR = Color(214, 226, 170)
PEST_BURST = Color(120, 76, 158)
WILT_BURST = Color(140, 128, 112)
GAIN_COLOR = Color(255, 226, 140)
WARN_COLOR = Color(236, 120, 96)

NIGHT_COLOR = (16, 26, 72)
NIGHT_MAX_ALPHA = 110
"""Alpha of the night wash at `clock.darkness() == 1.0`."""

ALERT_COLOR = (190, 50, 50)
ALERT_MAX_ALPHA = 95
ALERT_DECAY = 1.3
"""Per-second decay of the outbreak alert flash; ~0.75s to clear."""

SWAY_SPEED = 1.6
"""Radians per second the idle sway's sine advances at."""

SWAY_AMPLITUDE = 1.6
"""Peak sway offset in pixels -- a breath, not a wobble."""

POP_START_SCALE = 0.7
"""Where a plant's pop tween starts from -- it grows into the overshoot."""

POP_DURATION = 0.3
"""Seconds a pop tween takes to reach (and briefly pass) its target scale."""


@dataclass
class _PlantVisual:
    """Per-plant animation state, keyed by entity id.

    Owned by the canvas, not `PlantComponent` -- this is pure presentation
    (how a stage change *reads*), not simulation state the save schema or
    any system needs, so it stays out of the data-only component.
    """

    known_stage: str
    pop_tween: Tween | None = None
    sway_seed: float = 0.0


class GardenGridCanvas(Canvas):
    """Draws the plot and turns a left click into a `Cell`.

    Attributes:
        on_cell_clicked: Called with the clicked cell. Set by the owning
            scene rather than passed to `__init__` -- the same
            `on_click`-after-construction pattern every stock widget uses.
    """

    def __init__(
        self,
        position: Vector2,
        grid: GardenGrid,
        entity_manager: EntityManager,
        audio: AudioManager | None = None,
    ) -> None:
        """Initialize the canvas over `grid`'s full pixel extent.

        Args:
            position: Top-left corner, in screen space.
            grid: The plot to draw and click into.
            entity_manager: Where planted entities live -- the canvas reads
                each occupied cell's `PlantComponent` to draw it, rather
                than the tilemap's `flora` layer keeping a second copy of
                the species/colour as tile data.
            audio: Plays the SFX matching each `celebrate_*`/stage-change
                beat. Optional and defaulted to `None` so every existing
                test that constructs a bare canvas keeps working unchanged.
        """
        super().__init__(
            position, Vector2(GRID_WIDTH * TILE_SIZE, GRID_HEIGHT * TILE_SIZE)
        )
        self.grid = grid
        self._entity_manager = entity_manager
        self._audio = audio
        self.on_cell_clicked: Callable[[Cell], None] | None = None
        self._motes = Motes()
        self._labels = FloatingLabels()
        self._visuals: dict[str, _PlantVisual] = {}
        self._elapsed = 0.0
        self._alert = 0.0
        self.hover_cell: Cell | None = None
        """The last cell the cursor was over. It is kept when the cursor
        leaves the plot for the tool dock, so the inspector still has
        something to show."""
        self.darkness = 0.0
        """0.0 in daylight up to 1.0 at night; set by the scene from
        `clock.darkness()` and drawn as a translucent wash."""

    def _cell_at(self, position: Vector2) -> Cell | None:
        """The cell under a screen-space `position`, or None off-grid."""
        local_x = position.x - self.rect.x
        local_y = position.y - self.rect.y
        if local_x < 0 or local_y < 0:
            return None
        cell = (int(local_x // TILE_SIZE), int(local_y // TILE_SIZE))
        return cell if self.grid.in_bounds(cell) else None

    def _cell_screen_center(self, cell: Cell) -> Vector2:
        """The screen-space centre of `cell`."""
        local_center = cell_to_world(cell, TILE_SIZE)
        return Vector2(self.rect.x + local_center.x, self.rect.y + local_center.y)

    def _play(self, path: str) -> None:
        """Play `path` through `self._audio`, if one was supplied."""
        if self._audio is not None:
            self._audio.play_sfx(path)

    def celebrate_till(self, cell: Cell) -> None:
        """Kick up a puff of dust -- call right after a successful till.

        Args:
            cell: The cell that was just tilled.
        """
        self._motes.burst(
            self._cell_screen_center(cell), TILL_DUST, count=7, speed=35.0, life=0.4
        )
        self._play(SFX_TILL)

    def celebrate_water(self, cell: Cell) -> None:
        """Splash a few droplets -- call right after a successful watering.

        Args:
            cell: The cell that was just watered.
        """
        self._motes.burst(
            self._cell_screen_center(cell), WATER_DROPLET, count=6, speed=25.0, life=0.5
        )
        self._play(SFX_WATER)

    def celebrate_harvest(self, cell: Cell, species_id: str) -> None:
        """Burst the species' colour plus a gold accent -- the loop's payoff.

        A bigger, two-colour beat than a stage change's burst: harvesting
        is the moment the loop closes and the cell is free again, and
        should read as more rewarding than "the plant grew a bit".

        Args:
            cell: The cell that was just harvested.
            species_id: The harvested plant's species, for its colour.
        """
        species = SPECIES_TABLE.get(species_id)
        color = species.color if species is not None else Color.WHITE
        center = self._cell_screen_center(cell)
        self._motes.burst(center, color, count=16, speed=70.0, life=0.7)
        self._motes.burst(center, HARVEST_GOLD, count=8, speed=90.0, life=0.5)
        self._play(SFX_HARVEST)

    def celebrate_seed(self, cell: Cell, species_id: str) -> None:
        """A quieter beat than a sale -- collecting a seed, not Sementes.

        Covers both of `economy.harvest_cell`'s non-credit outcomes: a
        weed pulled for generic seed stock, and a crop left `"overripe"`
        for a specific one. Deliberately not `celebrate_harvest`'s bigger,
        gold-accented burst -- a seed is a smaller, different kind of win.

        Args:
            cell: The cell that was just collected.
            species_id: The collected plant's species, for its colour.
        """
        species = SPECIES_TABLE.get(species_id)
        color = species.color if species is not None else Color.WHITE
        center = self._cell_screen_center(cell)
        self._motes.burst(center, color, count=6, speed=35.0, life=0.5)
        self._motes.burst(center, SEED_COLOR, count=6, speed=40.0, life=0.5)
        self._play(SFX_SEED)

    def celebrate_compost(self, cell: Cell) -> None:
        """Turn over some rich earth -- call right after a successful compost.

        Args:
            cell: The cell that was just composted.
        """
        self._motes.burst(
            self._cell_screen_center(cell), COMPOST_COLOR, count=9, speed=30.0, life=0.6
        )
        self._play(SFX_COMPOST)

    def celebrate_build(self, cell: Cell, kind: str) -> None:
        """Puff the structure's colour as it goes down.

        Args:
            cell: Where it was placed.
            kind: A key of `structures.STRUCTURE_TABLE`.
        """
        structure = STRUCTURE_TABLE.get(kind)
        color = structure.color if structure is not None else Color.WHITE
        self._motes.burst(
            self._cell_screen_center(cell), color, count=12, speed=50.0, life=0.6
        )
        self._play(SFX_BUILD)

    def celebrate_spray(self, cell: Cell) -> None:
        """Puff a pale chemical cloud over the cell and its eight neighbours.

        Args:
            cell: The centre of the spray.
        """
        for target in [cell, *neighbors8(cell)]:
            if self.grid.in_bounds(target):
                self._motes.burst(
                    self._cell_screen_center(target),
                    SPRAY_COLOR,
                    count=5,
                    speed=28.0,
                    life=0.7,
                    radius=4.0,
                )
        self._play(SFX_SPRAY)

    def spawn_label(self, cell: Cell, text: str, color: Color) -> None:
        """Float a short piece of text up from a cell: "+16", "Need 15".

        Args:
            cell: The cell it rises from.
            text: What to show.
            color: Its colour; it fades out as it rises.
        """
        self._labels.spawn(
            text, self._cell_screen_center(cell) - Vector2(10, 14), color
        )

    def flash_alert(self) -> None:
        """Wash the plot red for a moment -- an outbreak just began."""
        self._alert = 1.0

    def _process_input(
        self, event_type: UIEventType, position: Vector2, button: int
    ) -> bool:
        if event_type == UIEventType.MOUSE_MOVE:
            cell = self._cell_at(position)
            if cell is not None:
                self.hover_cell = cell
        if event_type == UIEventType.MOUSE_DOWN and button == 1:
            cell = self._cell_at(position)
            if cell is not None:
                # A click points the inspector at the tile too: there is no
                # hover on a touch screen, and it is the tile you just acted on.
                self.hover_cell = cell
                if self.on_cell_clicked is not None:
                    self.on_cell_clicked(cell)
                return True
        return super()._process_input(event_type, position, button)

    def update(self, dt: float) -> None:
        """Advance particles and every planted entity's pop/sway animation."""
        super().update(dt)
        self._elapsed += dt
        self._motes.update(dt)
        self._labels.update(dt)
        self._alert = max(0.0, self._alert - dt * ALERT_DECAY)
        self._update_plant_visuals(dt)

    def _update_plant_visuals(self, dt: float) -> None:
        live_ids: set[str] = set()
        for cell, entity_id in self.grid.plant_at.items():
            live_ids.add(entity_id)
            entity = self._entity_manager.get_entity(entity_id)
            if entity is None or not entity.has_component(PlantComponent):
                continue
            plant = entity.get_component(PlantComponent)

            visual = self._visuals.get(entity_id)
            if visual is None:
                # First frame this entity has been seen -- treat it the
                # same as a stage change: a pop and a burst, so planting
                # itself reads as an event and not just a shape appearing.
                visual = _PlantVisual(
                    known_stage=plant.growth_stage,
                    sway_seed=hash(entity_id) % 100 / 16.0,
                )
                self._visuals[entity_id] = visual
                self._start_pop(visual)
                self._celebrate_stage(cell, plant.species_id, plant.growth_stage)
                continue

            if plant.growth_stage != visual.known_stage:
                visual.known_stage = plant.growth_stage
                self._start_pop(visual)
                self._celebrate_stage(cell, plant.species_id, plant.growth_stage)
            elif visual.pop_tween is not None and visual.pop_tween.is_playing:
                visual.pop_tween.update(dt)

        # Drop tracking for anything no longer planted -- nothing removes a
        # plant yet in this phase, but a future harvest/death should not
        # leak an animation state entry forever.
        for stale_id in set(self._visuals) - live_ids:
            del self._visuals[stale_id]

    def _start_pop(self, visual: _PlantVisual) -> None:
        """(Re)start the grow-past-target-then-settle scale animation.

        `EASE_OUT_BACK` overshoots past its end value before landing on it
        exactly -- tweening up to the resting scale with it *is* the "pop
        bigger than target, then return" beat, with no separate return leg
        to hand-author.
        """
        tween = Tween(
            start_value=POP_START_SCALE,
            end_value=1.0,
            duration=POP_DURATION,
            easing=EasingType.EASE_OUT_BACK,
        )
        tween.start()
        visual.pop_tween = tween

    def _celebrate_stage(self, cell: Cell, species_id: str, stage: str) -> None:
        """Burst on a stage change -- in the pest's colour if it is bad news."""
        species = SPECIES_TABLE.get(species_id)
        color = species.color if species is not None else Color.WHITE
        sfx = SFX_GROW_STAGE
        if stage == "infested":
            color = PEST_BURST
            sfx = SFX_INFESTED
        elif stage == "dying":
            color = WILT_BURST
            sfx = SFX_DYING
        elif stage == "seedling":
            sfx = SFX_PLANT
        self._motes.burst(
            self._cell_screen_center(cell), color, count=10, speed=45.0, life=0.55
        )
        self._play(sfx)

    def render(self, renderer: UIRenderer) -> None:
        """Do nothing -- `UIManager` still calls this, but drawing itself
        happens in `render_world()`. See the module docstring for why."""

    def render_world(self, renderer: IRenderer) -> None:
        """Draw every soil cell, then whatever occupies it, then particles.

        Called directly by `scenes.GardenScene.render()`, not by
        `UIManager` -- see the module docstring.
        """
        terrain = self.grid.tilemap.layers["terrain"]
        for y in range(GRID_HEIGHT):
            for x in range(GRID_WIDTH):
                gid = terrain.get_tile((x, y))
                kind = self.grid.tilemap.properties_for(gid).get("kind", "raw_dirt")
                rect = Rect(
                    self.rect.x + x * TILE_SIZE,
                    self.rect.y + y * TILE_SIZE,
                    TILE_SIZE,
                    TILE_SIZE,
                )
                soil = self.grid.soil_at((x, y))
                art.draw_soil_tile(
                    renderer,
                    rect,
                    kind,
                    moisture=soil.moisture,
                    degraded=soil.is_chemically_degraded,
                )
                if soil.pest_pressure > 0.05:
                    art.draw_pest_marks(
                        renderer, rect, soil.pest_pressure, self._elapsed
                    )

        self._draw_structures(renderer)
        self._draw_plants(renderer)
        self._motes.render(renderer)
        self._labels.render(renderer)
        if self.darkness > 0.0:
            renderer.draw_rect(
                self.rect, Color(*NIGHT_COLOR, int(NIGHT_MAX_ALPHA * self.darkness))
            )
        if self._alert > 0.0:
            renderer.draw_rect(
                self.rect, Color(*ALERT_COLOR, int(ALERT_MAX_ALPHA * self._alert))
            )
        # No `for child in self.children: child.render(...)` here: nothing
        # ever adds a child to this canvas (it draws the whole plot itself),
        # and a generic UI child would expect `UIRenderer` regardless.
        renderer.end_frame()

    def _draw_plants(self, renderer: IRenderer) -> None:
        """Draw every planted cell's plant, at its current growth stage.

        Reads each occupant's `PlantComponent` fresh rather than caching a
        colour on the tile -- the `flora` layer only marks a cell occupied
        (see `garden_grid.py`'s module docstring), never what is growing
        there.
        """
        for cell, entity_id in self.grid.plant_at.items():
            entity = self._entity_manager.get_entity(entity_id)
            if entity is None or not entity.has_component(PlantComponent):
                continue
            plant = entity.get_component(PlantComponent)
            species = SPECIES_TABLE.get(plant.species_id)
            if species is None:
                continue

            visual = self._visuals.get(entity_id)
            pop_scale = 1.0
            sway = 0.0
            if visual is not None:
                if visual.pop_tween is not None:
                    current = visual.pop_tween.current_value
                    pop_scale = current if isinstance(current, float) else 1.0
                sway = (
                    math.sin(self._elapsed * SWAY_SPEED + visual.sway_seed)
                    * SWAY_AMPLITUDE
                )

            art.draw_plant(
                renderer,
                self._cell_screen_center(cell),
                species.color,
                plant.growth_stage,
                pop_scale=pop_scale,
                sway=sway,
                elapsed=self._elapsed,
            )

    def _structure_at(self, cell: Cell) -> AutomationComponent | None:
        entity_id = self.grid.automation_at.get(cell)
        if entity_id is None:
            return None
        entity = self._entity_manager.get_entity(entity_id)
        if entity is None or not entity.has_component(AutomationComponent):
            return None
        return entity.get_component(AutomationComponent)

    def _draw_structures(self, renderer: IRenderer) -> None:
        """Draw every placed structure, then each sensor's readout bars.

        The readouts go under the plants but over the soil, on every cell
        any sensor reaches -- collected into a set first so two overlapping
        sensors do not draw the same bars twice.
        """
        sensed: set[Cell] = set()
        for cell in self.grid.automation_at:
            structure = self._structure_at(cell)
            if structure is None:
                continue
            art.draw_structure(
                renderer,
                self._cell_rect(cell),
                structure.kind,
                powered=structure.powered,
                elapsed=self._elapsed,
            )
            if structure.kind == "soil_sensor":
                sensed.update(
                    area(self.grid, cell, STRUCTURE_TABLE["soil_sensor"].radius)
                )

        for cell in sensed:
            soil = self.grid.soil_at(cell)
            art.draw_sensor_readout(
                renderer,
                self._cell_rect(cell),
                soil.moisture,
                soil.organic_matter,
                soil.pest_pressure,
            )

    def _cell_rect(self, cell: Cell) -> Rect:
        """The screen rectangle of `cell`."""
        return Rect(
            self.rect.x + cell[0] * TILE_SIZE,
            self.rect.y + cell[1] * TILE_SIZE,
            TILE_SIZE,
            TILE_SIZE,
        )
